pareto

In [2]:
import pandas as pd
import oapackage

In [3]:
#cp
df = pd.read_csv(r'C:\\Users\\Quint\\Documents\\EPA\\Thesis\\ENC_Py3_mra-main\\enrichment_final\\ENC_Py3_mra-main_2\\ENC_Py3_mra-main\\EU_output\\mmr_2\\2. theta_cp_coarse_cal_output_2.csv',index_col='theta_cp')
df['Metric_3']=1-df['Metric_3']
df2=df.values
df2=df2.transpose()
pareto=oapackage.ParetoDoubleLong()

for ii in range(0, df2.shape[1]):
    w=oapackage.doubleVector((df2[0,ii], df2[1,ii], df2[2,ii]))
    pareto.addvalue(w, ii)

pareto.show(verbose=1)
list_pareto=pareto.allindices()
df['Pareto']='No'
list_2=['no']*len(df)
for i in list_pareto:
    list_2[i]='Yes'
df['Pareto']=list_2
df

Pareto: 11 optimal values, 11 objects

          Metric_1  Metric_2  Metric_3 Pareto
theta_cp
0.0000    0.609431  0.051753  0.928158     no
0.0025    0.609853  0.053038  0.930551    Yes
0.0050    0.609609  0.053298  0.933530    Yes
0.0075    0.609133  0.053405  0.937182    Yes
0.0100    0.608267  0.052933  0.941295    Yes
0.0125    0.607389  0.053436  0.946078    Yes
0.0150    0.605743  0.053017  0.951092    Yes
0.0175    0.604231  0.053961  0.956223    Yes
0.0200    0.601535  0.053796  0.961006    Yes
0.0225    0.598854  0.054803  0.964987    Yes
0.0250    0.595770  0.056251  0.968738    Yes
0.0275    0.591785  0.056709  0.968809    Yes
0.0300    0.587284  0.056446  0.964515     no
0.0325    0.582603  0.056093  0.960209     no
0.0350    0.577128  0.054303  0.956743     no
0.0375    0.572038  0.053336  0.953027     no
0.0400    0.566952  0.052197  0.949977     no
0.0425    0.561801  0.051383  0.946694     no
0.0450    0.556755  0.050752  0.944551     no
0.0475    0.551287  0.048450  0.942711     no
0.0500    0.545572  0.045465  0.941121     no

In [106]:
#ct
df = pd.read_csv(r'C:\\Users\\Quint\\Documents\\EPA\\Thesis\\ENC_Py3_mra-main\\enrichment_final\\ENC_Py3_mra-main_2\\ENC_Py3_mra-main\\EU_output\\mmr_2\\3. theta_ct_coarse_cal_output_2.csv',index_col='theta_ct')
df['Metric_3']=1-df['Metric_3']
df2=df.values
df2=df2.transpose()
pareto=oapackage.ParetoDoubleLong()

for ii in range(0, df2.shape[1]):
    w=oapackage.doubleVector((df2[0,ii], df2[1,ii], df2[2,ii]))
    pareto.addvalue(w, ii)

pareto.show(verbose=1)
list_pareto=pareto.allindices()
df['Pareto']='No'
list_2=['no']*len(df)
for i in list_pareto:
    list_2[i]='Yes'
df['Pareto']=list_2
df

Pareto: 6 optimal values, 6 objects

          Metric_1  Metric_2  Metric_3 Pareto
theta_ct
0.000     0.595122  0.035603  0.887177     no
0.001     0.595913  0.035583  0.888266     no
0.002     0.597190  0.036386  0.889673     no
0.003     0.598785  0.037726  0.891333     no
0.004     0.600547  0.039701  0.893259     no
0.005     0.601700  0.040725  0.895437     no
0.006     0.602569  0.041406  0.897592     no
0.007     0.603695  0.042892  0.899621     no
0.008     0.604682  0.044035  0.902321     no
0.009     0.605155  0.044401  0.905290     no
0.010     0.605544  0.045196  0.908613    Yes
0.011     0.605050  0.043633  0.912534     no
0.012     0.604706  0.042766  0.916796     no
0.013     0.603800  0.041473  0.920386     no
0.014     0.604063  0.041994  0.922612     no
0.015     0.604706  0.043410  0.925983     no
0.016     0.605470  0.045499  0.931308    Yes
0.017     0.604939  0.046982  0.939004    Yes
0.018     0.603701  0.049668  0.949160    Yes
0.019     0.600670  0.052512  0.960369    Yes
0.020     0.595770  0.056251  0.968738    Yes

In [3]:
#it
df = pd.read_csv(r'C:\\Users\\Quint\\Documents\\EPA\\Thesis\\ENC_Py3_mra-main\\enrichment_final\\ENC_Py3_mra-main_2\\ENC_Py3_mra-main\\EU_output\\mmr_2\\1. theta_it_coarse_cal_output_mmr_6_7-9.csv',index_col='theta_it')
df['Metric_3']=1-df['Metric_3']
df2=df.values
df2=df2.transpose()
pareto=oapackage.ParetoDoubleLong()

for ii in range(0, df2.shape[1]):
    w=oapackage.doubleVector((df2[0,ii], df2[1,ii], df2[2,ii]))
    pareto.addvalue(w, ii)

pareto.show(verbose=1)
list_pareto=pareto.allindices()
df['Pareto']='No'
list_2=['no']*len(df)
for i in list_pareto:
    list_2[i]='Yes'
df['Pareto']=list_2
df

Pareto: 8 optimal values, 8 objects

          Metric_1  Metric_2  Metric_3 Pareto
theta_it
0.000     0.608057  0.095854  0.885896     no
0.005     0.610067  0.098854  0.891966     no
0.010     0.613306  0.104341  0.898533     no
0.015     0.616263  0.110480  0.902551     no
0.020     0.618008  0.114638  0.904241     no
0.025     0.619272  0.117949  0.907082     no
0.030     0.620297  0.120691  0.910227     no
0.035     0.621861  0.123793  0.914332     no
0.040     0.622765  0.125495  0.918972     no
0.045     0.623878  0.127125  0.924763     no
0.050     0.624878  0.128581  0.931352     no
0.055     0.625267  0.128639  0.938372     no
0.060     0.626426  0.130424  0.946356     no
0.065     0.627445  0.132245  0.954505    Yes
0.070     0.627684  0.132243  0.951905    Yes
0.075     0.627911  0.132550  0.947156    Yes
0.080     0.628331  0.133508  0.942329    Yes
0.085     0.628682  0.134583  0.937895    Yes
0.090     0.628579  0.134778  0.934428    Yes
0.095     0.628497  0.135195  0.931561    Yes
0.100     0.628238  0.135827  0.929109    Yes

In [4]:
#cp
df = pd.read_csv(r'C:\\Users\\Quint\\Documents\\EPA\\Thesis\\ENC_Py3_mra-main\\enrichment_final\\ENC_Py3_mra-main_2\\ENC_Py3_mra-main\\EU_output\\mmr_2\\2. theta_cp_coarse_cal_output_mmr_6.csv',index_col='theta_cp')
df['Metric_3']=1-df['Metric_3']
df2=df.values
df2=df2.transpose()
pareto=oapackage.ParetoDoubleLong()

for ii in range(0, df2.shape[1]):
    w=oapackage.doubleVector((df2[0,ii], df2[1,ii], df2[2,ii]))
    pareto.addvalue(w, ii)

pareto.show(verbose=1)
list_pareto=pareto.allindices()
df['Pareto']='No'
list_2=['no']*len(df)
for i in list_pareto:
    list_2[i]='Yes'
df['Pareto']=list_2
df

Pareto: 11 optimal values, 11 objects

          Metric_1  Metric_2  Metric_3 Pareto
theta_cp
0.0000    0.609431  0.051753  0.928158     no
0.0025    0.609853  0.053038  0.930551    Yes
0.0050    0.609609  0.053298  0.933530    Yes
0.0075    0.609133  0.053405  0.937182    Yes
0.0100    0.608267  0.052933  0.941295    Yes
0.0125    0.607389  0.053436  0.946078    Yes
0.0150    0.605743  0.053017  0.951092    Yes
0.0175    0.604231  0.053961  0.956223    Yes
0.0200    0.601535  0.053796  0.961006    Yes
0.0225    0.598854  0.054803  0.964987    Yes
0.0250    0.595770  0.056251  0.968738    Yes
0.0275    0.591785  0.056709  0.968809    Yes
0.0300    0.587284  0.056446  0.964515     no
0.0325    0.582603  0.056093  0.960209     no
0.0350    0.577128  0.054303  0.956743     no
0.0375    0.572038  0.053336  0.953027     no
0.0400    0.566952  0.052197  0.949977     no
0.0425    0.561801  0.051383  0.946694     no
0.0450    0.556755  0.050752  0.944551     no
0.0475    0.551287  0.048450  0.942711     no
0.0500    0.545572  0.045465  0.941121     no

In [ ]:
"2. theta_cp_coarse_cal_output_mmr_6.csv"